import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		// init
		int mySum = 0;
		int counter2 = 0;
		int counter3 = 0;
		int counter4 = 0;

		for (int i = 0; i < T; i++){
			boolean boy = false;
			boolean girl = false;
			double choice;
			int num_children = 0;

			// checks 
			do{
			choice = generator.nextDouble();
			if (choice < 0.5){
				boy = true;
				num_children++;
			}
			else{
				girl = true;
				num_children++;
			}
			}while((!boy) || (!girl));
			
			if(num_children == 2){
				counter2 ++;
			}
			if (num_children == 3){
				counter3++;
			}
			if (num_children >= 4){
				counter4++;
			}
			mySum += num_children;
		}
		double average = (double) mySum / T;
		int myMax = Math.max(counter2, counter3);
		myMax = Math.max(myMax, counter4);
		String common;
		if (myMax == counter2){
			common = "2";
		}
		else if (myMax == counter3){
			common = "3";
		}
		else{
			common = "4 or more";
		}
		System.out.println("Average: " + average + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + counter2);
		System.out.println("Number of families with 3 children: " + counter3);
		System.out.println("Number of families with 4 or more children: " + counter4);
		System.out.println("The most common number of children is " + common +".");
	}
}
